### ISSUE TITLE
Is it acceptable by Nile university?

### ISSUE THREAD

**Issue by yaserabdelaziz** [mr-eyes/NU-Thesis-Template#1]
Hi Mohamed,
Is this master's thesis template acceptable by Nile university?

Respectfully,

**Comment by mr-eyes** [comment]
Hi @yaserabdelaziz ,

Yes, and mine was approved the last year by the University. The template is also available on Overleaf. Feel free to edit and open PRs :)

**Comment by yaserabdelaziz** [comment]
Thanks for adding it to Github. That's of a great benefit. :)
